#pragma once
#include <Windows.h>

enum AppMessages
{
    WM_USER_EVENT = WM_USER + 1,
    WM_POST_MSG_TO_WEBVIEW,
    WM_PROCESS_WEBVIEW_MESSAGE,
    WM_USER_SUBSCRIBE,
    WM_USER_UNSUBSCRIBE,
    WM_EXECUTE_SCRIPT_WEBVIEW,
    WM_USER_DISPATCH,
    WM_USER_PROCESS_DATA_QUEUE,
    WM_USER_CREATE_ENVIRONMENT,
    WM_PROCESS_SHARED_BUFFER
};
